baseURL = 'https://muncus.github.io/'
languageCode = 'en-us'
title = "Marc's Links"

[module]
  [[module.imports]]
    path = 'github.com/cx48/LucentLink-Hugo'
    disable = false

[params]
  googleAnalytics = "G-B2BQBY4RGY"
